# Generated by Django 2.2.5 on 2019-09-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=100)),
                ('discount_percent', models.CharField(max_length=100)),
                ('max_use', models.CharField(default=3, max_length=100)),
                ('used', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
