# Generated by Django 2.2.5 on 2019-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=100),
        ),
    ]
