# Generated by Django 2.2.5 on 2019-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20190906_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='max_use',
            field=models.BigIntegerField(default=3, max_length=100),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used',
            field=models.BigIntegerField(default=0, max_length=100),
        ),
    ]
