# Generated by Django 2.2.5 on 2019-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_auto_20190907_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=100, null=True),
        ),
    ]
